### ISSUE TITLE
Swap to Tailwind CSS

### ISSUE THREAD

**Issue by ellaharrasser** [ethanharrasser/vibrato#9]
Install Tailwind CSS to the project, then migrate existing styles to Tailwind utility classes. Create custom Tailwind classes if needed for heavily reused items (cards, buttons, etc.).

**Comment by Avinashshiyani** [comment]
I can help with tailwind css .

**Comment by ellaharrasser** [comment]
Hey, I would love for you to help out, but this project is really meant to be solo, sorry !

**Comment by Avinashshiyani** [comment]
Ok no problem Enjoy TailwindCss.
